import './global.css';
import Providers from "./providers";
import Link from 'next/link'
import ThemeSwitcher from './components/ThemeSwitcher'


export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Providers>
        <header className='py-6'>
            <nav className='container flex items-center justify-between'>
              <ul className='flex gap-6 flex-row'>
                <li>
                  <Link href='/woo-orders'>Orders</Link>
                </li>
                <li>
                  <Link href='/purchases'>Licenses</Link>
                </li>
              </ul>
              <ThemeSwitcher />
            </nav>
          </header>
          <main>{children}</main>
          <footer></footer>
        </Providers>
        </body>
    </html>
  );
}
