import './global.css';
import Providers from "./providers";
import Header from "@/components/Header";


export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className='h-screen'>
        <Providers>
          <Header/>
          <main className='container flex justify-center items-center h-full'>{children}</main>
          <footer></footer>
        </Providers>
        </body>
    </html>
  );
}
